// Code generated by go-swagger; DO NOT EDIT.

package apiregistration_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchApiregistrationV1beta1APIServiceHandlerFunc turns a function with the right signature into a patch apiregistration v1beta1 API service handler
type PatchApiregistrationV1beta1APIServiceHandlerFunc func(PatchApiregistrationV1beta1APIServiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchApiregistrationV1beta1APIServiceHandlerFunc) Handle(params PatchApiregistrationV1beta1APIServiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchApiregistrationV1beta1APIServiceHandler interface for that can handle valid patch apiregistration v1beta1 API service params
type PatchApiregistrationV1beta1APIServiceHandler interface {
	Handle(PatchApiregistrationV1beta1APIServiceParams, interface{}) middleware.Responder
}

// NewPatchApiregistrationV1beta1APIService creates a new http.Handler for the patch apiregistration v1beta1 API service operation
func NewPatchApiregistrationV1beta1APIService(ctx *middleware.Context, handler PatchApiregistrationV1beta1APIServiceHandler) *PatchApiregistrationV1beta1APIService {
	return &PatchApiregistrationV1beta1APIService{Context: ctx, Handler: handler}
}

/*PatchApiregistrationV1beta1APIService swagger:route PATCH /apis/apiregistration.k8s.io/v1beta1/apiservices/{name} apiregistration_v1beta1 patchApiregistrationV1beta1ApiService

partially update the specified APIService

*/
type PatchApiregistrationV1beta1APIService struct {
	Context *middleware.Context
	Handler PatchApiregistrationV1beta1APIServiceHandler
}

func (o *PatchApiregistrationV1beta1APIService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchApiregistrationV1beta1APIServiceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
