// Code generated by go-swagger; DO NOT EDIT.

package apiextensions_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchApiextensionsV1CustomResourceDefinitionHandlerFunc turns a function with the right signature into a patch apiextensions v1 custom resource definition handler
type PatchApiextensionsV1CustomResourceDefinitionHandlerFunc func(PatchApiextensionsV1CustomResourceDefinitionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchApiextensionsV1CustomResourceDefinitionHandlerFunc) Handle(params PatchApiextensionsV1CustomResourceDefinitionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchApiextensionsV1CustomResourceDefinitionHandler interface for that can handle valid patch apiextensions v1 custom resource definition params
type PatchApiextensionsV1CustomResourceDefinitionHandler interface {
	Handle(PatchApiextensionsV1CustomResourceDefinitionParams, interface{}) middleware.Responder
}

// NewPatchApiextensionsV1CustomResourceDefinition creates a new http.Handler for the patch apiextensions v1 custom resource definition operation
func NewPatchApiextensionsV1CustomResourceDefinition(ctx *middleware.Context, handler PatchApiextensionsV1CustomResourceDefinitionHandler) *PatchApiextensionsV1CustomResourceDefinition {
	return &PatchApiextensionsV1CustomResourceDefinition{Context: ctx, Handler: handler}
}

/*PatchApiextensionsV1CustomResourceDefinition swagger:route PATCH /apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name} apiextensions_v1 patchApiextensionsV1CustomResourceDefinition

partially update the specified CustomResourceDefinition

*/
type PatchApiextensionsV1CustomResourceDefinition struct {
	Context *middleware.Context
	Handler PatchApiextensionsV1CustomResourceDefinitionHandler
}

func (o *PatchApiextensionsV1CustomResourceDefinition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchApiextensionsV1CustomResourceDefinitionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
