// Code generated by go-swagger; DO NOT EDIT.

package rbac_authorization_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateRbacAuthorizationV1ClusterRoleBindingHandlerFunc turns a function with the right signature into a create rbac authorization v1 cluster role binding handler
type CreateRbacAuthorizationV1ClusterRoleBindingHandlerFunc func(CreateRbacAuthorizationV1ClusterRoleBindingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRbacAuthorizationV1ClusterRoleBindingHandlerFunc) Handle(params CreateRbacAuthorizationV1ClusterRoleBindingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateRbacAuthorizationV1ClusterRoleBindingHandler interface for that can handle valid create rbac authorization v1 cluster role binding params
type CreateRbacAuthorizationV1ClusterRoleBindingHandler interface {
	Handle(CreateRbacAuthorizationV1ClusterRoleBindingParams, interface{}) middleware.Responder
}

// NewCreateRbacAuthorizationV1ClusterRoleBinding creates a new http.Handler for the create rbac authorization v1 cluster role binding operation
func NewCreateRbacAuthorizationV1ClusterRoleBinding(ctx *middleware.Context, handler CreateRbacAuthorizationV1ClusterRoleBindingHandler) *CreateRbacAuthorizationV1ClusterRoleBinding {
	return &CreateRbacAuthorizationV1ClusterRoleBinding{Context: ctx, Handler: handler}
}

/*CreateRbacAuthorizationV1ClusterRoleBinding swagger:route POST /apis/rbac.authorization.k8s.io/v1/clusterrolebindings rbacAuthorization_v1 createRbacAuthorizationV1ClusterRoleBinding

create a ClusterRoleBinding

*/
type CreateRbacAuthorizationV1ClusterRoleBinding struct {
	Context *middleware.Context
	Handler CreateRbacAuthorizationV1ClusterRoleBindingHandler
}

func (o *CreateRbacAuthorizationV1ClusterRoleBinding) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateRbacAuthorizationV1ClusterRoleBindingParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
