// Code generated by go-swagger; DO NOT EDIT.

package rbac_authorization_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListRbacAuthorizationV1ClusterRoleHandlerFunc turns a function with the right signature into a list rbac authorization v1 cluster role handler
type ListRbacAuthorizationV1ClusterRoleHandlerFunc func(ListRbacAuthorizationV1ClusterRoleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListRbacAuthorizationV1ClusterRoleHandlerFunc) Handle(params ListRbacAuthorizationV1ClusterRoleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListRbacAuthorizationV1ClusterRoleHandler interface for that can handle valid list rbac authorization v1 cluster role params
type ListRbacAuthorizationV1ClusterRoleHandler interface {
	Handle(ListRbacAuthorizationV1ClusterRoleParams, interface{}) middleware.Responder
}

// NewListRbacAuthorizationV1ClusterRole creates a new http.Handler for the list rbac authorization v1 cluster role operation
func NewListRbacAuthorizationV1ClusterRole(ctx *middleware.Context, handler ListRbacAuthorizationV1ClusterRoleHandler) *ListRbacAuthorizationV1ClusterRole {
	return &ListRbacAuthorizationV1ClusterRole{Context: ctx, Handler: handler}
}

/*ListRbacAuthorizationV1ClusterRole swagger:route GET /apis/rbac.authorization.k8s.io/v1/clusterroles rbacAuthorization_v1 listRbacAuthorizationV1ClusterRole

list or watch objects of kind ClusterRole

*/
type ListRbacAuthorizationV1ClusterRole struct {
	Context *middleware.Context
	Handler ListRbacAuthorizationV1ClusterRoleHandler
}

func (o *ListRbacAuthorizationV1ClusterRole) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListRbacAuthorizationV1ClusterRoleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
