// Code generated by go-swagger; DO NOT EDIT.

package apiextensions_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceApiextensionsV1beta1CustomResourceDefinitionHandlerFunc turns a function with the right signature into a replace apiextensions v1beta1 custom resource definition handler
type ReplaceApiextensionsV1beta1CustomResourceDefinitionHandlerFunc func(ReplaceApiextensionsV1beta1CustomResourceDefinitionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceApiextensionsV1beta1CustomResourceDefinitionHandlerFunc) Handle(params ReplaceApiextensionsV1beta1CustomResourceDefinitionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceApiextensionsV1beta1CustomResourceDefinitionHandler interface for that can handle valid replace apiextensions v1beta1 custom resource definition params
type ReplaceApiextensionsV1beta1CustomResourceDefinitionHandler interface {
	Handle(ReplaceApiextensionsV1beta1CustomResourceDefinitionParams, interface{}) middleware.Responder
}

// NewReplaceApiextensionsV1beta1CustomResourceDefinition creates a new http.Handler for the replace apiextensions v1beta1 custom resource definition operation
func NewReplaceApiextensionsV1beta1CustomResourceDefinition(ctx *middleware.Context, handler ReplaceApiextensionsV1beta1CustomResourceDefinitionHandler) *ReplaceApiextensionsV1beta1CustomResourceDefinition {
	return &ReplaceApiextensionsV1beta1CustomResourceDefinition{Context: ctx, Handler: handler}
}

/*ReplaceApiextensionsV1beta1CustomResourceDefinition swagger:route PUT /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name} apiextensions_v1beta1 replaceApiextensionsV1beta1CustomResourceDefinition

replace the specified CustomResourceDefinition

*/
type ReplaceApiextensionsV1beta1CustomResourceDefinition struct {
	Context *middleware.Context
	Handler ReplaceApiextensionsV1beta1CustomResourceDefinitionHandler
}

func (o *ReplaceApiextensionsV1beta1CustomResourceDefinition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceApiextensionsV1beta1CustomResourceDefinitionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
