// Code generated by go-swagger; DO NOT EDIT.

package admissionregistration_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandlerFunc turns a function with the right signature into a delete admissionregistration v1 collection validating webhook configuration handler
type DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandlerFunc func(DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandlerFunc) Handle(params DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandler interface for that can handle valid delete admissionregistration v1 collection validating webhook configuration params
type DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandler interface {
	Handle(DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationParams, interface{}) middleware.Responder
}

// NewDeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration creates a new http.Handler for the delete admissionregistration v1 collection validating webhook configuration operation
func NewDeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration(ctx *middleware.Context, handler DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandler) *DeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration {
	return &DeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration{Context: ctx, Handler: handler}
}

/*DeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration swagger:route DELETE /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations admissionregistration_v1 deleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration

delete collection of ValidatingWebhookConfiguration

*/
type DeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration struct {
	Context *middleware.Context
	Handler DeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationHandler
}

func (o *DeleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAdmissionregistrationV1CollectionValidatingWebhookConfigurationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
