// Code generated by go-swagger; DO NOT EDIT.

package auditregistration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/oar-team/batkube/models"
)

// GetAuditregistrationAPIGroupOKCode is the HTTP code returned for type GetAuditregistrationAPIGroupOK
const GetAuditregistrationAPIGroupOKCode int = 200

/*GetAuditregistrationAPIGroupOK OK

swagger:response getAuditregistrationApiGroupOK
*/
type GetAuditregistrationAPIGroupOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup `json:"body,omitempty"`
}

// NewGetAuditregistrationAPIGroupOK creates GetAuditregistrationAPIGroupOK with default headers values
func NewGetAuditregistrationAPIGroupOK() *GetAuditregistrationAPIGroupOK {

	return &GetAuditregistrationAPIGroupOK{}
}

// WithPayload adds the payload to the get auditregistration Api group o k response
func (o *GetAuditregistrationAPIGroupOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup) *GetAuditregistrationAPIGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auditregistration Api group o k response
func (o *GetAuditregistrationAPIGroupOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditregistrationAPIGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditregistrationAPIGroupUnauthorizedCode is the HTTP code returned for type GetAuditregistrationAPIGroupUnauthorized
const GetAuditregistrationAPIGroupUnauthorizedCode int = 401

/*GetAuditregistrationAPIGroupUnauthorized Unauthorized

swagger:response getAuditregistrationApiGroupUnauthorized
*/
type GetAuditregistrationAPIGroupUnauthorized struct {
}

// NewGetAuditregistrationAPIGroupUnauthorized creates GetAuditregistrationAPIGroupUnauthorized with default headers values
func NewGetAuditregistrationAPIGroupUnauthorized() *GetAuditregistrationAPIGroupUnauthorized {

	return &GetAuditregistrationAPIGroupUnauthorized{}
}

// WriteResponse to the client
func (o *GetAuditregistrationAPIGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
