// Code generated by go-swagger; DO NOT EDIT.

package auditregistration_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.com/ryax-tech/internships/2020/scheduling_simulation/batkube/models"
)

// CreateAuditregistrationV1alpha1AuditSinkOKCode is the HTTP code returned for type CreateAuditregistrationV1alpha1AuditSinkOK
const CreateAuditregistrationV1alpha1AuditSinkOKCode int = 200

/*CreateAuditregistrationV1alpha1AuditSinkOK OK

swagger:response createAuditregistrationV1alpha1AuditSinkOK
*/
type CreateAuditregistrationV1alpha1AuditSinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink `json:"body,omitempty"`
}

// NewCreateAuditregistrationV1alpha1AuditSinkOK creates CreateAuditregistrationV1alpha1AuditSinkOK with default headers values
func NewCreateAuditregistrationV1alpha1AuditSinkOK() *CreateAuditregistrationV1alpha1AuditSinkOK {

	return &CreateAuditregistrationV1alpha1AuditSinkOK{}
}

// WithPayload adds the payload to the create auditregistration v1alpha1 audit sink o k response
func (o *CreateAuditregistrationV1alpha1AuditSinkOK) WithPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) *CreateAuditregistrationV1alpha1AuditSinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create auditregistration v1alpha1 audit sink o k response
func (o *CreateAuditregistrationV1alpha1AuditSinkOK) SetPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAuditregistrationV1alpha1AuditSinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAuditregistrationV1alpha1AuditSinkCreatedCode is the HTTP code returned for type CreateAuditregistrationV1alpha1AuditSinkCreated
const CreateAuditregistrationV1alpha1AuditSinkCreatedCode int = 201

/*CreateAuditregistrationV1alpha1AuditSinkCreated Created

swagger:response createAuditregistrationV1alpha1AuditSinkCreated
*/
type CreateAuditregistrationV1alpha1AuditSinkCreated struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink `json:"body,omitempty"`
}

// NewCreateAuditregistrationV1alpha1AuditSinkCreated creates CreateAuditregistrationV1alpha1AuditSinkCreated with default headers values
func NewCreateAuditregistrationV1alpha1AuditSinkCreated() *CreateAuditregistrationV1alpha1AuditSinkCreated {

	return &CreateAuditregistrationV1alpha1AuditSinkCreated{}
}

// WithPayload adds the payload to the create auditregistration v1alpha1 audit sink created response
func (o *CreateAuditregistrationV1alpha1AuditSinkCreated) WithPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) *CreateAuditregistrationV1alpha1AuditSinkCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create auditregistration v1alpha1 audit sink created response
func (o *CreateAuditregistrationV1alpha1AuditSinkCreated) SetPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAuditregistrationV1alpha1AuditSinkCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAuditregistrationV1alpha1AuditSinkAcceptedCode is the HTTP code returned for type CreateAuditregistrationV1alpha1AuditSinkAccepted
const CreateAuditregistrationV1alpha1AuditSinkAcceptedCode int = 202

/*CreateAuditregistrationV1alpha1AuditSinkAccepted Accepted

swagger:response createAuditregistrationV1alpha1AuditSinkAccepted
*/
type CreateAuditregistrationV1alpha1AuditSinkAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink `json:"body,omitempty"`
}

// NewCreateAuditregistrationV1alpha1AuditSinkAccepted creates CreateAuditregistrationV1alpha1AuditSinkAccepted with default headers values
func NewCreateAuditregistrationV1alpha1AuditSinkAccepted() *CreateAuditregistrationV1alpha1AuditSinkAccepted {

	return &CreateAuditregistrationV1alpha1AuditSinkAccepted{}
}

// WithPayload adds the payload to the create auditregistration v1alpha1 audit sink accepted response
func (o *CreateAuditregistrationV1alpha1AuditSinkAccepted) WithPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) *CreateAuditregistrationV1alpha1AuditSinkAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create auditregistration v1alpha1 audit sink accepted response
func (o *CreateAuditregistrationV1alpha1AuditSinkAccepted) SetPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAuditregistrationV1alpha1AuditSinkAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAuditregistrationV1alpha1AuditSinkUnauthorizedCode is the HTTP code returned for type CreateAuditregistrationV1alpha1AuditSinkUnauthorized
const CreateAuditregistrationV1alpha1AuditSinkUnauthorizedCode int = 401

/*CreateAuditregistrationV1alpha1AuditSinkUnauthorized Unauthorized

swagger:response createAuditregistrationV1alpha1AuditSinkUnauthorized
*/
type CreateAuditregistrationV1alpha1AuditSinkUnauthorized struct {
}

// NewCreateAuditregistrationV1alpha1AuditSinkUnauthorized creates CreateAuditregistrationV1alpha1AuditSinkUnauthorized with default headers values
func NewCreateAuditregistrationV1alpha1AuditSinkUnauthorized() *CreateAuditregistrationV1alpha1AuditSinkUnauthorized {

	return &CreateAuditregistrationV1alpha1AuditSinkUnauthorized{}
}

// WriteResponse to the client
func (o *CreateAuditregistrationV1alpha1AuditSinkUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
