// Code generated by go-swagger; DO NOT EDIT.

package auditregistration_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchAuditregistrationV1alpha1AuditSinkHandlerFunc turns a function with the right signature into a patch auditregistration v1alpha1 audit sink handler
type PatchAuditregistrationV1alpha1AuditSinkHandlerFunc func(PatchAuditregistrationV1alpha1AuditSinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchAuditregistrationV1alpha1AuditSinkHandlerFunc) Handle(params PatchAuditregistrationV1alpha1AuditSinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchAuditregistrationV1alpha1AuditSinkHandler interface for that can handle valid patch auditregistration v1alpha1 audit sink params
type PatchAuditregistrationV1alpha1AuditSinkHandler interface {
	Handle(PatchAuditregistrationV1alpha1AuditSinkParams, interface{}) middleware.Responder
}

// NewPatchAuditregistrationV1alpha1AuditSink creates a new http.Handler for the patch auditregistration v1alpha1 audit sink operation
func NewPatchAuditregistrationV1alpha1AuditSink(ctx *middleware.Context, handler PatchAuditregistrationV1alpha1AuditSinkHandler) *PatchAuditregistrationV1alpha1AuditSink {
	return &PatchAuditregistrationV1alpha1AuditSink{Context: ctx, Handler: handler}
}

/*PatchAuditregistrationV1alpha1AuditSink swagger:route PATCH /apis/auditregistration.k8s.io/v1alpha1/auditsinks/{name} auditregistration_v1alpha1 patchAuditregistrationV1alpha1AuditSink

partially update the specified AuditSink

*/
type PatchAuditregistrationV1alpha1AuditSink struct {
	Context *middleware.Context
	Handler PatchAuditregistrationV1alpha1AuditSinkHandler
}

func (o *PatchAuditregistrationV1alpha1AuditSink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchAuditregistrationV1alpha1AuditSinkParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
