// Code generated by go-swagger; DO NOT EDIT.

package auditregistration_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.com/ryax-tech/internships/2020/scheduling_simulation/batkube/models"
)

// ReadAuditregistrationV1alpha1AuditSinkOKCode is the HTTP code returned for type ReadAuditregistrationV1alpha1AuditSinkOK
const ReadAuditregistrationV1alpha1AuditSinkOKCode int = 200

/*ReadAuditregistrationV1alpha1AuditSinkOK OK

swagger:response readAuditregistrationV1alpha1AuditSinkOK
*/
type ReadAuditregistrationV1alpha1AuditSinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink `json:"body,omitempty"`
}

// NewReadAuditregistrationV1alpha1AuditSinkOK creates ReadAuditregistrationV1alpha1AuditSinkOK with default headers values
func NewReadAuditregistrationV1alpha1AuditSinkOK() *ReadAuditregistrationV1alpha1AuditSinkOK {

	return &ReadAuditregistrationV1alpha1AuditSinkOK{}
}

// WithPayload adds the payload to the read auditregistration v1alpha1 audit sink o k response
func (o *ReadAuditregistrationV1alpha1AuditSinkOK) WithPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) *ReadAuditregistrationV1alpha1AuditSinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read auditregistration v1alpha1 audit sink o k response
func (o *ReadAuditregistrationV1alpha1AuditSinkOK) SetPayload(payload *models.IoK8sAPIAuditregistrationV1alpha1AuditSink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadAuditregistrationV1alpha1AuditSinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReadAuditregistrationV1alpha1AuditSinkUnauthorizedCode is the HTTP code returned for type ReadAuditregistrationV1alpha1AuditSinkUnauthorized
const ReadAuditregistrationV1alpha1AuditSinkUnauthorizedCode int = 401

/*ReadAuditregistrationV1alpha1AuditSinkUnauthorized Unauthorized

swagger:response readAuditregistrationV1alpha1AuditSinkUnauthorized
*/
type ReadAuditregistrationV1alpha1AuditSinkUnauthorized struct {
}

// NewReadAuditregistrationV1alpha1AuditSinkUnauthorized creates ReadAuditregistrationV1alpha1AuditSinkUnauthorized with default headers values
func NewReadAuditregistrationV1alpha1AuditSinkUnauthorized() *ReadAuditregistrationV1alpha1AuditSinkUnauthorized {

	return &ReadAuditregistrationV1alpha1AuditSinkUnauthorized{}
}

// WriteResponse to the client
func (o *ReadAuditregistrationV1alpha1AuditSinkUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
