// Code generated by go-swagger; DO NOT EDIT.

package admissionregistration_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandlerFunc turns a function with the right signature into a list admissionregistration v1beta1 mutating webhook configuration handler
type ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandlerFunc func(ListAdmissionregistrationV1beta1MutatingWebhookConfigurationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandlerFunc) Handle(params ListAdmissionregistrationV1beta1MutatingWebhookConfigurationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandler interface for that can handle valid list admissionregistration v1beta1 mutating webhook configuration params
type ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandler interface {
	Handle(ListAdmissionregistrationV1beta1MutatingWebhookConfigurationParams, interface{}) middleware.Responder
}

// NewListAdmissionregistrationV1beta1MutatingWebhookConfiguration creates a new http.Handler for the list admissionregistration v1beta1 mutating webhook configuration operation
func NewListAdmissionregistrationV1beta1MutatingWebhookConfiguration(ctx *middleware.Context, handler ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandler) *ListAdmissionregistrationV1beta1MutatingWebhookConfiguration {
	return &ListAdmissionregistrationV1beta1MutatingWebhookConfiguration{Context: ctx, Handler: handler}
}

/*ListAdmissionregistrationV1beta1MutatingWebhookConfiguration swagger:route GET /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations admissionregistration_v1beta1 listAdmissionregistrationV1beta1MutatingWebhookConfiguration

list or watch objects of kind MutatingWebhookConfiguration

*/
type ListAdmissionregistrationV1beta1MutatingWebhookConfiguration struct {
	Context *middleware.Context
	Handler ListAdmissionregistrationV1beta1MutatingWebhookConfigurationHandler
}

func (o *ListAdmissionregistrationV1beta1MutatingWebhookConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAdmissionregistrationV1beta1MutatingWebhookConfigurationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
