// Code generated by go-swagger; DO NOT EDIT.

package flowcontrol_apiserver_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandlerFunc turns a function with the right signature into a replace flowcontrol apiserver v1alpha1 flow schema handler
type ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandlerFunc func(ReplaceFlowcontrolApiserverV1alpha1FlowSchemaParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandlerFunc) Handle(params ReplaceFlowcontrolApiserverV1alpha1FlowSchemaParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandler interface for that can handle valid replace flowcontrol apiserver v1alpha1 flow schema params
type ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandler interface {
	Handle(ReplaceFlowcontrolApiserverV1alpha1FlowSchemaParams, interface{}) middleware.Responder
}

// NewReplaceFlowcontrolApiserverV1alpha1FlowSchema creates a new http.Handler for the replace flowcontrol apiserver v1alpha1 flow schema operation
func NewReplaceFlowcontrolApiserverV1alpha1FlowSchema(ctx *middleware.Context, handler ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandler) *ReplaceFlowcontrolApiserverV1alpha1FlowSchema {
	return &ReplaceFlowcontrolApiserverV1alpha1FlowSchema{Context: ctx, Handler: handler}
}

/*ReplaceFlowcontrolApiserverV1alpha1FlowSchema swagger:route PUT /apis/flowcontrol.apiserver.k8s.io/v1alpha1/flowschemas/{name} flowcontrolApiserver_v1alpha1 replaceFlowcontrolApiserverV1alpha1FlowSchema

replace the specified FlowSchema

*/
type ReplaceFlowcontrolApiserverV1alpha1FlowSchema struct {
	Context *middleware.Context
	Handler ReplaceFlowcontrolApiserverV1alpha1FlowSchemaHandler
}

func (o *ReplaceFlowcontrolApiserverV1alpha1FlowSchema) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceFlowcontrolApiserverV1alpha1FlowSchemaParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
