// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Kubernetes
//
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: unversioned
//
//  Consumes:
//    - */*
//    - application/json
//    - application/json-patch+json
//    - application/merge-patch+json
//    - application/strategic-merge-patch+json
//    - application/vnd.kubernetes.protobuf
//    - application/apply-patch+yaml
//    - application/yaml
//
//  Produces:
//    - */*
//    - application/json
//    - application/vnd.kubernetes.protobuf
//    - text/plain
//    - application/yaml
//
// swagger:meta
package restapi
