---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      annotations:
    spec:
      schedulerName: bashScheduler
      containers:
      - name: nginx
        image: nginx:1.11-alpine
        ports:
        - containerPort: 80
