// Code generated by go-swagger; DO NOT EDIT.

package node_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteNodeV1alpha1CollectionRuntimeClassHandlerFunc turns a function with the right signature into a delete node v1alpha1 collection runtime class handler
type DeleteNodeV1alpha1CollectionRuntimeClassHandlerFunc func(DeleteNodeV1alpha1CollectionRuntimeClassParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNodeV1alpha1CollectionRuntimeClassHandlerFunc) Handle(params DeleteNodeV1alpha1CollectionRuntimeClassParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteNodeV1alpha1CollectionRuntimeClassHandler interface for that can handle valid delete node v1alpha1 collection runtime class params
type DeleteNodeV1alpha1CollectionRuntimeClassHandler interface {
	Handle(DeleteNodeV1alpha1CollectionRuntimeClassParams, interface{}) middleware.Responder
}

// NewDeleteNodeV1alpha1CollectionRuntimeClass creates a new http.Handler for the delete node v1alpha1 collection runtime class operation
func NewDeleteNodeV1alpha1CollectionRuntimeClass(ctx *middleware.Context, handler DeleteNodeV1alpha1CollectionRuntimeClassHandler) *DeleteNodeV1alpha1CollectionRuntimeClass {
	return &DeleteNodeV1alpha1CollectionRuntimeClass{Context: ctx, Handler: handler}
}

/*DeleteNodeV1alpha1CollectionRuntimeClass swagger:route DELETE /apis/node.k8s.io/v1alpha1/runtimeclasses node_v1alpha1 deleteNodeV1alpha1CollectionRuntimeClass

delete collection of RuntimeClass

*/
type DeleteNodeV1alpha1CollectionRuntimeClass struct {
	Context *middleware.Context
	Handler DeleteNodeV1alpha1CollectionRuntimeClassHandler
}

func (o *DeleteNodeV1alpha1CollectionRuntimeClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteNodeV1alpha1CollectionRuntimeClassParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
