// Code generated by go-swagger; DO NOT EDIT.

package node_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteNodeV1alpha1RuntimeClassHandlerFunc turns a function with the right signature into a delete node v1alpha1 runtime class handler
type DeleteNodeV1alpha1RuntimeClassHandlerFunc func(DeleteNodeV1alpha1RuntimeClassParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNodeV1alpha1RuntimeClassHandlerFunc) Handle(params DeleteNodeV1alpha1RuntimeClassParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteNodeV1alpha1RuntimeClassHandler interface for that can handle valid delete node v1alpha1 runtime class params
type DeleteNodeV1alpha1RuntimeClassHandler interface {
	Handle(DeleteNodeV1alpha1RuntimeClassParams, interface{}) middleware.Responder
}

// NewDeleteNodeV1alpha1RuntimeClass creates a new http.Handler for the delete node v1alpha1 runtime class operation
func NewDeleteNodeV1alpha1RuntimeClass(ctx *middleware.Context, handler DeleteNodeV1alpha1RuntimeClassHandler) *DeleteNodeV1alpha1RuntimeClass {
	return &DeleteNodeV1alpha1RuntimeClass{Context: ctx, Handler: handler}
}

/*DeleteNodeV1alpha1RuntimeClass swagger:route DELETE /apis/node.k8s.io/v1alpha1/runtimeclasses/{name} node_v1alpha1 deleteNodeV1alpha1RuntimeClass

delete a RuntimeClass

*/
type DeleteNodeV1alpha1RuntimeClass struct {
	Context *middleware.Context
	Handler DeleteNodeV1alpha1RuntimeClassHandler
}

func (o *DeleteNodeV1alpha1RuntimeClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteNodeV1alpha1RuntimeClassParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
