// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConnectCoreV1PatchNodeProxyHandlerFunc turns a function with the right signature into a connect core v1 patch node proxy handler
type ConnectCoreV1PatchNodeProxyHandlerFunc func(ConnectCoreV1PatchNodeProxyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectCoreV1PatchNodeProxyHandlerFunc) Handle(params ConnectCoreV1PatchNodeProxyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConnectCoreV1PatchNodeProxyHandler interface for that can handle valid connect core v1 patch node proxy params
type ConnectCoreV1PatchNodeProxyHandler interface {
	Handle(ConnectCoreV1PatchNodeProxyParams, interface{}) middleware.Responder
}

// NewConnectCoreV1PatchNodeProxy creates a new http.Handler for the connect core v1 patch node proxy operation
func NewConnectCoreV1PatchNodeProxy(ctx *middleware.Context, handler ConnectCoreV1PatchNodeProxyHandler) *ConnectCoreV1PatchNodeProxy {
	return &ConnectCoreV1PatchNodeProxy{Context: ctx, Handler: handler}
}

/*ConnectCoreV1PatchNodeProxy swagger:route PATCH /api/v1/nodes/{name}/proxy core_v1 connectCoreV1PatchNodeProxy

connect PATCH requests to proxy of Node

*/
type ConnectCoreV1PatchNodeProxy struct {
	Context *middleware.Context
	Handler ConnectCoreV1PatchNodeProxyHandler
}

func (o *ConnectCoreV1PatchNodeProxy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConnectCoreV1PatchNodeProxyParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
