// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConnectCoreV1OptionsNodeProxyHandlerFunc turns a function with the right signature into a connect core v1 options node proxy handler
type ConnectCoreV1OptionsNodeProxyHandlerFunc func(ConnectCoreV1OptionsNodeProxyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectCoreV1OptionsNodeProxyHandlerFunc) Handle(params ConnectCoreV1OptionsNodeProxyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConnectCoreV1OptionsNodeProxyHandler interface for that can handle valid connect core v1 options node proxy params
type ConnectCoreV1OptionsNodeProxyHandler interface {
	Handle(ConnectCoreV1OptionsNodeProxyParams, interface{}) middleware.Responder
}

// NewConnectCoreV1OptionsNodeProxy creates a new http.Handler for the connect core v1 options node proxy operation
func NewConnectCoreV1OptionsNodeProxy(ctx *middleware.Context, handler ConnectCoreV1OptionsNodeProxyHandler) *ConnectCoreV1OptionsNodeProxy {
	return &ConnectCoreV1OptionsNodeProxy{Context: ctx, Handler: handler}
}

/*ConnectCoreV1OptionsNodeProxy swagger:route OPTIONS /api/v1/nodes/{name}/proxy core_v1 connectCoreV1OptionsNodeProxy

connect OPTIONS requests to proxy of Node

*/
type ConnectCoreV1OptionsNodeProxy struct {
	Context *middleware.Context
	Handler ConnectCoreV1OptionsNodeProxyHandler
}

func (o *ConnectCoreV1OptionsNodeProxy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConnectCoreV1OptionsNodeProxyParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
