// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConnectCoreV1DeleteNamespacedPodProxyWithPathHandlerFunc turns a function with the right signature into a connect core v1 delete namespaced pod proxy with path handler
type ConnectCoreV1DeleteNamespacedPodProxyWithPathHandlerFunc func(ConnectCoreV1DeleteNamespacedPodProxyWithPathParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectCoreV1DeleteNamespacedPodProxyWithPathHandlerFunc) Handle(params ConnectCoreV1DeleteNamespacedPodProxyWithPathParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConnectCoreV1DeleteNamespacedPodProxyWithPathHandler interface for that can handle valid connect core v1 delete namespaced pod proxy with path params
type ConnectCoreV1DeleteNamespacedPodProxyWithPathHandler interface {
	Handle(ConnectCoreV1DeleteNamespacedPodProxyWithPathParams, interface{}) middleware.Responder
}

// NewConnectCoreV1DeleteNamespacedPodProxyWithPath creates a new http.Handler for the connect core v1 delete namespaced pod proxy with path operation
func NewConnectCoreV1DeleteNamespacedPodProxyWithPath(ctx *middleware.Context, handler ConnectCoreV1DeleteNamespacedPodProxyWithPathHandler) *ConnectCoreV1DeleteNamespacedPodProxyWithPath {
	return &ConnectCoreV1DeleteNamespacedPodProxyWithPath{Context: ctx, Handler: handler}
}

/*ConnectCoreV1DeleteNamespacedPodProxyWithPath swagger:route DELETE /api/v1/namespaces/{namespace}/pods/{name}/proxy/{path} core_v1 connectCoreV1DeleteNamespacedPodProxyWithPath

connect DELETE requests to proxy of Pod

*/
type ConnectCoreV1DeleteNamespacedPodProxyWithPath struct {
	Context *middleware.Context
	Handler ConnectCoreV1DeleteNamespacedPodProxyWithPathHandler
}

func (o *ConnectCoreV1DeleteNamespacedPodProxyWithPath) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConnectCoreV1DeleteNamespacedPodProxyWithPathParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
