// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConnectCoreV1HeadNamespacedPodProxyWithPathHandlerFunc turns a function with the right signature into a connect core v1 head namespaced pod proxy with path handler
type ConnectCoreV1HeadNamespacedPodProxyWithPathHandlerFunc func(ConnectCoreV1HeadNamespacedPodProxyWithPathParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectCoreV1HeadNamespacedPodProxyWithPathHandlerFunc) Handle(params ConnectCoreV1HeadNamespacedPodProxyWithPathParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConnectCoreV1HeadNamespacedPodProxyWithPathHandler interface for that can handle valid connect core v1 head namespaced pod proxy with path params
type ConnectCoreV1HeadNamespacedPodProxyWithPathHandler interface {
	Handle(ConnectCoreV1HeadNamespacedPodProxyWithPathParams, interface{}) middleware.Responder
}

// NewConnectCoreV1HeadNamespacedPodProxyWithPath creates a new http.Handler for the connect core v1 head namespaced pod proxy with path operation
func NewConnectCoreV1HeadNamespacedPodProxyWithPath(ctx *middleware.Context, handler ConnectCoreV1HeadNamespacedPodProxyWithPathHandler) *ConnectCoreV1HeadNamespacedPodProxyWithPath {
	return &ConnectCoreV1HeadNamespacedPodProxyWithPath{Context: ctx, Handler: handler}
}

/*ConnectCoreV1HeadNamespacedPodProxyWithPath swagger:route HEAD /api/v1/namespaces/{namespace}/pods/{name}/proxy/{path} core_v1 connectCoreV1HeadNamespacedPodProxyWithPath

connect HEAD requests to proxy of Pod

*/
type ConnectCoreV1HeadNamespacedPodProxyWithPath struct {
	Context *middleware.Context
	Handler ConnectCoreV1HeadNamespacedPodProxyWithPathHandler
}

func (o *ConnectCoreV1HeadNamespacedPodProxyWithPath) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConnectCoreV1HeadNamespacedPodProxyWithPathParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
