// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConnectCoreV1OptionsNamespacedPodProxyHandlerFunc turns a function with the right signature into a connect core v1 options namespaced pod proxy handler
type ConnectCoreV1OptionsNamespacedPodProxyHandlerFunc func(ConnectCoreV1OptionsNamespacedPodProxyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectCoreV1OptionsNamespacedPodProxyHandlerFunc) Handle(params ConnectCoreV1OptionsNamespacedPodProxyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConnectCoreV1OptionsNamespacedPodProxyHandler interface for that can handle valid connect core v1 options namespaced pod proxy params
type ConnectCoreV1OptionsNamespacedPodProxyHandler interface {
	Handle(ConnectCoreV1OptionsNamespacedPodProxyParams, interface{}) middleware.Responder
}

// NewConnectCoreV1OptionsNamespacedPodProxy creates a new http.Handler for the connect core v1 options namespaced pod proxy operation
func NewConnectCoreV1OptionsNamespacedPodProxy(ctx *middleware.Context, handler ConnectCoreV1OptionsNamespacedPodProxyHandler) *ConnectCoreV1OptionsNamespacedPodProxy {
	return &ConnectCoreV1OptionsNamespacedPodProxy{Context: ctx, Handler: handler}
}

/*ConnectCoreV1OptionsNamespacedPodProxy swagger:route OPTIONS /api/v1/namespaces/{namespace}/pods/{name}/proxy core_v1 connectCoreV1OptionsNamespacedPodProxy

connect OPTIONS requests to proxy of Pod

*/
type ConnectCoreV1OptionsNamespacedPodProxy struct {
	Context *middleware.Context
	Handler ConnectCoreV1OptionsNamespacedPodProxyHandler
}

func (o *ConnectCoreV1OptionsNamespacedPodProxy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConnectCoreV1OptionsNamespacedPodProxyParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
