// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCoreV1NodeHandlerFunc turns a function with the right signature into a delete core v1 node handler
type DeleteCoreV1NodeHandlerFunc func(DeleteCoreV1NodeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCoreV1NodeHandlerFunc) Handle(params DeleteCoreV1NodeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCoreV1NodeHandler interface for that can handle valid delete core v1 node params
type DeleteCoreV1NodeHandler interface {
	Handle(DeleteCoreV1NodeParams, interface{}) middleware.Responder
}

// NewDeleteCoreV1Node creates a new http.Handler for the delete core v1 node operation
func NewDeleteCoreV1Node(ctx *middleware.Context, handler DeleteCoreV1NodeHandler) *DeleteCoreV1Node {
	return &DeleteCoreV1Node{Context: ctx, Handler: handler}
}

/*DeleteCoreV1Node swagger:route DELETE /api/v1/nodes/{name} core_v1 deleteCoreV1Node

delete a Node

*/
type DeleteCoreV1Node struct {
	Context *middleware.Context
	Handler DeleteCoreV1NodeHandler
}

func (o *DeleteCoreV1Node) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCoreV1NodeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
