// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCoreV1NamespacedResourceQuotaHandlerFunc turns a function with the right signature into a delete core v1 namespaced resource quota handler
type DeleteCoreV1NamespacedResourceQuotaHandlerFunc func(DeleteCoreV1NamespacedResourceQuotaParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCoreV1NamespacedResourceQuotaHandlerFunc) Handle(params DeleteCoreV1NamespacedResourceQuotaParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCoreV1NamespacedResourceQuotaHandler interface for that can handle valid delete core v1 namespaced resource quota params
type DeleteCoreV1NamespacedResourceQuotaHandler interface {
	Handle(DeleteCoreV1NamespacedResourceQuotaParams, interface{}) middleware.Responder
}

// NewDeleteCoreV1NamespacedResourceQuota creates a new http.Handler for the delete core v1 namespaced resource quota operation
func NewDeleteCoreV1NamespacedResourceQuota(ctx *middleware.Context, handler DeleteCoreV1NamespacedResourceQuotaHandler) *DeleteCoreV1NamespacedResourceQuota {
	return &DeleteCoreV1NamespacedResourceQuota{Context: ctx, Handler: handler}
}

/*DeleteCoreV1NamespacedResourceQuota swagger:route DELETE /api/v1/namespaces/{namespace}/resourcequotas/{name} core_v1 deleteCoreV1NamespacedResourceQuota

delete a ResourceQuota

*/
type DeleteCoreV1NamespacedResourceQuota struct {
	Context *middleware.Context
	Handler DeleteCoreV1NamespacedResourceQuotaHandler
}

func (o *DeleteCoreV1NamespacedResourceQuota) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCoreV1NamespacedResourceQuotaParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
