// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCoreV1NamespacedServiceHandlerFunc turns a function with the right signature into a delete core v1 namespaced service handler
type DeleteCoreV1NamespacedServiceHandlerFunc func(DeleteCoreV1NamespacedServiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCoreV1NamespacedServiceHandlerFunc) Handle(params DeleteCoreV1NamespacedServiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCoreV1NamespacedServiceHandler interface for that can handle valid delete core v1 namespaced service params
type DeleteCoreV1NamespacedServiceHandler interface {
	Handle(DeleteCoreV1NamespacedServiceParams, interface{}) middleware.Responder
}

// NewDeleteCoreV1NamespacedService creates a new http.Handler for the delete core v1 namespaced service operation
func NewDeleteCoreV1NamespacedService(ctx *middleware.Context, handler DeleteCoreV1NamespacedServiceHandler) *DeleteCoreV1NamespacedService {
	return &DeleteCoreV1NamespacedService{Context: ctx, Handler: handler}
}

/*DeleteCoreV1NamespacedService swagger:route DELETE /api/v1/namespaces/{namespace}/services/{name} core_v1 deleteCoreV1NamespacedService

delete a Service

*/
type DeleteCoreV1NamespacedService struct {
	Context *middleware.Context
	Handler DeleteCoreV1NamespacedServiceHandler
}

func (o *DeleteCoreV1NamespacedService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCoreV1NamespacedServiceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
