// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCoreV1PersistentVolumeHandlerFunc turns a function with the right signature into a delete core v1 persistent volume handler
type DeleteCoreV1PersistentVolumeHandlerFunc func(DeleteCoreV1PersistentVolumeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCoreV1PersistentVolumeHandlerFunc) Handle(params DeleteCoreV1PersistentVolumeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCoreV1PersistentVolumeHandler interface for that can handle valid delete core v1 persistent volume params
type DeleteCoreV1PersistentVolumeHandler interface {
	Handle(DeleteCoreV1PersistentVolumeParams, interface{}) middleware.Responder
}

// NewDeleteCoreV1PersistentVolume creates a new http.Handler for the delete core v1 persistent volume operation
func NewDeleteCoreV1PersistentVolume(ctx *middleware.Context, handler DeleteCoreV1PersistentVolumeHandler) *DeleteCoreV1PersistentVolume {
	return &DeleteCoreV1PersistentVolume{Context: ctx, Handler: handler}
}

/*DeleteCoreV1PersistentVolume swagger:route DELETE /api/v1/persistentvolumes/{name} core_v1 deleteCoreV1PersistentVolume

delete a PersistentVolume

*/
type DeleteCoreV1PersistentVolume struct {
	Context *middleware.Context
	Handler DeleteCoreV1PersistentVolumeHandler
}

func (o *DeleteCoreV1PersistentVolume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCoreV1PersistentVolumeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
