// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCoreV1NamespacedReplicationControllerHandlerFunc turns a function with the right signature into a delete core v1 namespaced replication controller handler
type DeleteCoreV1NamespacedReplicationControllerHandlerFunc func(DeleteCoreV1NamespacedReplicationControllerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCoreV1NamespacedReplicationControllerHandlerFunc) Handle(params DeleteCoreV1NamespacedReplicationControllerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCoreV1NamespacedReplicationControllerHandler interface for that can handle valid delete core v1 namespaced replication controller params
type DeleteCoreV1NamespacedReplicationControllerHandler interface {
	Handle(DeleteCoreV1NamespacedReplicationControllerParams, interface{}) middleware.Responder
}

// NewDeleteCoreV1NamespacedReplicationController creates a new http.Handler for the delete core v1 namespaced replication controller operation
func NewDeleteCoreV1NamespacedReplicationController(ctx *middleware.Context, handler DeleteCoreV1NamespacedReplicationControllerHandler) *DeleteCoreV1NamespacedReplicationController {
	return &DeleteCoreV1NamespacedReplicationController{Context: ctx, Handler: handler}
}

/*DeleteCoreV1NamespacedReplicationController swagger:route DELETE /api/v1/namespaces/{namespace}/replicationcontrollers/{name} core_v1 deleteCoreV1NamespacedReplicationController

delete a ReplicationController

*/
type DeleteCoreV1NamespacedReplicationController struct {
	Context *middleware.Context
	Handler DeleteCoreV1NamespacedReplicationControllerHandler
}

func (o *DeleteCoreV1NamespacedReplicationController) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCoreV1NamespacedReplicationControllerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
