// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.com/ryax-tech/internships/2020/scheduling_simulation/batkube/models"
)

// PatchCoreV1NamespacedResourceQuotaOKCode is the HTTP code returned for type PatchCoreV1NamespacedResourceQuotaOK
const PatchCoreV1NamespacedResourceQuotaOKCode int = 200

/*PatchCoreV1NamespacedResourceQuotaOK OK

swagger:response patchCoreV1NamespacedResourceQuotaOK
*/
type PatchCoreV1NamespacedResourceQuotaOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPICoreV1ResourceQuota `json:"body,omitempty"`
}

// NewPatchCoreV1NamespacedResourceQuotaOK creates PatchCoreV1NamespacedResourceQuotaOK with default headers values
func NewPatchCoreV1NamespacedResourceQuotaOK() *PatchCoreV1NamespacedResourceQuotaOK {

	return &PatchCoreV1NamespacedResourceQuotaOK{}
}

// WithPayload adds the payload to the patch core v1 namespaced resource quota o k response
func (o *PatchCoreV1NamespacedResourceQuotaOK) WithPayload(payload *models.IoK8sAPICoreV1ResourceQuota) *PatchCoreV1NamespacedResourceQuotaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch core v1 namespaced resource quota o k response
func (o *PatchCoreV1NamespacedResourceQuotaOK) SetPayload(payload *models.IoK8sAPICoreV1ResourceQuota) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchCoreV1NamespacedResourceQuotaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchCoreV1NamespacedResourceQuotaUnauthorizedCode is the HTTP code returned for type PatchCoreV1NamespacedResourceQuotaUnauthorized
const PatchCoreV1NamespacedResourceQuotaUnauthorizedCode int = 401

/*PatchCoreV1NamespacedResourceQuotaUnauthorized Unauthorized

swagger:response patchCoreV1NamespacedResourceQuotaUnauthorized
*/
type PatchCoreV1NamespacedResourceQuotaUnauthorized struct {
}

// NewPatchCoreV1NamespacedResourceQuotaUnauthorized creates PatchCoreV1NamespacedResourceQuotaUnauthorized with default headers values
func NewPatchCoreV1NamespacedResourceQuotaUnauthorized() *PatchCoreV1NamespacedResourceQuotaUnauthorized {

	return &PatchCoreV1NamespacedResourceQuotaUnauthorized{}
}

// WriteResponse to the client
func (o *PatchCoreV1NamespacedResourceQuotaUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
