// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.com/ryax-tech/internships/2020/scheduling_simulation/batkube/models"
)

// PatchCoreV1NamespacedServiceOKCode is the HTTP code returned for type PatchCoreV1NamespacedServiceOK
const PatchCoreV1NamespacedServiceOKCode int = 200

/*PatchCoreV1NamespacedServiceOK OK

swagger:response patchCoreV1NamespacedServiceOK
*/
type PatchCoreV1NamespacedServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPICoreV1Service `json:"body,omitempty"`
}

// NewPatchCoreV1NamespacedServiceOK creates PatchCoreV1NamespacedServiceOK with default headers values
func NewPatchCoreV1NamespacedServiceOK() *PatchCoreV1NamespacedServiceOK {

	return &PatchCoreV1NamespacedServiceOK{}
}

// WithPayload adds the payload to the patch core v1 namespaced service o k response
func (o *PatchCoreV1NamespacedServiceOK) WithPayload(payload *models.IoK8sAPICoreV1Service) *PatchCoreV1NamespacedServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch core v1 namespaced service o k response
func (o *PatchCoreV1NamespacedServiceOK) SetPayload(payload *models.IoK8sAPICoreV1Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchCoreV1NamespacedServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchCoreV1NamespacedServiceUnauthorizedCode is the HTTP code returned for type PatchCoreV1NamespacedServiceUnauthorized
const PatchCoreV1NamespacedServiceUnauthorizedCode int = 401

/*PatchCoreV1NamespacedServiceUnauthorized Unauthorized

swagger:response patchCoreV1NamespacedServiceUnauthorized
*/
type PatchCoreV1NamespacedServiceUnauthorized struct {
}

// NewPatchCoreV1NamespacedServiceUnauthorized creates PatchCoreV1NamespacedServiceUnauthorized with default headers values
func NewPatchCoreV1NamespacedServiceUnauthorized() *PatchCoreV1NamespacedServiceUnauthorized {

	return &PatchCoreV1NamespacedServiceUnauthorized{}
}

// WriteResponse to the client
func (o *PatchCoreV1NamespacedServiceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
