// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchCoreV1NamespacedServiceHandlerFunc turns a function with the right signature into a patch core v1 namespaced service handler
type PatchCoreV1NamespacedServiceHandlerFunc func(PatchCoreV1NamespacedServiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchCoreV1NamespacedServiceHandlerFunc) Handle(params PatchCoreV1NamespacedServiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchCoreV1NamespacedServiceHandler interface for that can handle valid patch core v1 namespaced service params
type PatchCoreV1NamespacedServiceHandler interface {
	Handle(PatchCoreV1NamespacedServiceParams, interface{}) middleware.Responder
}

// NewPatchCoreV1NamespacedService creates a new http.Handler for the patch core v1 namespaced service operation
func NewPatchCoreV1NamespacedService(ctx *middleware.Context, handler PatchCoreV1NamespacedServiceHandler) *PatchCoreV1NamespacedService {
	return &PatchCoreV1NamespacedService{Context: ctx, Handler: handler}
}

/*PatchCoreV1NamespacedService swagger:route PATCH /api/v1/namespaces/{namespace}/services/{name} core_v1 patchCoreV1NamespacedService

partially update the specified Service

*/
type PatchCoreV1NamespacedService struct {
	Context *middleware.Context
	Handler PatchCoreV1NamespacedServiceHandler
}

func (o *PatchCoreV1NamespacedService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchCoreV1NamespacedServiceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
