// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReadCoreV1NamespaceHandlerFunc turns a function with the right signature into a read core v1 namespace handler
type ReadCoreV1NamespaceHandlerFunc func(ReadCoreV1NamespaceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReadCoreV1NamespaceHandlerFunc) Handle(params ReadCoreV1NamespaceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReadCoreV1NamespaceHandler interface for that can handle valid read core v1 namespace params
type ReadCoreV1NamespaceHandler interface {
	Handle(ReadCoreV1NamespaceParams, interface{}) middleware.Responder
}

// NewReadCoreV1Namespace creates a new http.Handler for the read core v1 namespace operation
func NewReadCoreV1Namespace(ctx *middleware.Context, handler ReadCoreV1NamespaceHandler) *ReadCoreV1Namespace {
	return &ReadCoreV1Namespace{Context: ctx, Handler: handler}
}

/*ReadCoreV1Namespace swagger:route GET /api/v1/namespaces/{name} core_v1 readCoreV1Namespace

read the specified Namespace

*/
type ReadCoreV1Namespace struct {
	Context *middleware.Context
	Handler ReadCoreV1NamespaceHandler
}

func (o *ReadCoreV1Namespace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReadCoreV1NamespaceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
