// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceCoreV1NamespacedEndpointsHandlerFunc turns a function with the right signature into a replace core v1 namespaced endpoints handler
type ReplaceCoreV1NamespacedEndpointsHandlerFunc func(ReplaceCoreV1NamespacedEndpointsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceCoreV1NamespacedEndpointsHandlerFunc) Handle(params ReplaceCoreV1NamespacedEndpointsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceCoreV1NamespacedEndpointsHandler interface for that can handle valid replace core v1 namespaced endpoints params
type ReplaceCoreV1NamespacedEndpointsHandler interface {
	Handle(ReplaceCoreV1NamespacedEndpointsParams, interface{}) middleware.Responder
}

// NewReplaceCoreV1NamespacedEndpoints creates a new http.Handler for the replace core v1 namespaced endpoints operation
func NewReplaceCoreV1NamespacedEndpoints(ctx *middleware.Context, handler ReplaceCoreV1NamespacedEndpointsHandler) *ReplaceCoreV1NamespacedEndpoints {
	return &ReplaceCoreV1NamespacedEndpoints{Context: ctx, Handler: handler}
}

/*ReplaceCoreV1NamespacedEndpoints swagger:route PUT /api/v1/namespaces/{namespace}/endpoints/{name} core_v1 replaceCoreV1NamespacedEndpoints

replace the specified Endpoints

*/
type ReplaceCoreV1NamespacedEndpoints struct {
	Context *middleware.Context
	Handler ReplaceCoreV1NamespacedEndpointsHandler
}

func (o *ReplaceCoreV1NamespacedEndpoints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceCoreV1NamespacedEndpointsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
