// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceCoreV1NamespacedServiceStatusHandlerFunc turns a function with the right signature into a replace core v1 namespaced service status handler
type ReplaceCoreV1NamespacedServiceStatusHandlerFunc func(ReplaceCoreV1NamespacedServiceStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceCoreV1NamespacedServiceStatusHandlerFunc) Handle(params ReplaceCoreV1NamespacedServiceStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceCoreV1NamespacedServiceStatusHandler interface for that can handle valid replace core v1 namespaced service status params
type ReplaceCoreV1NamespacedServiceStatusHandler interface {
	Handle(ReplaceCoreV1NamespacedServiceStatusParams, interface{}) middleware.Responder
}

// NewReplaceCoreV1NamespacedServiceStatus creates a new http.Handler for the replace core v1 namespaced service status operation
func NewReplaceCoreV1NamespacedServiceStatus(ctx *middleware.Context, handler ReplaceCoreV1NamespacedServiceStatusHandler) *ReplaceCoreV1NamespacedServiceStatus {
	return &ReplaceCoreV1NamespacedServiceStatus{Context: ctx, Handler: handler}
}

/*ReplaceCoreV1NamespacedServiceStatus swagger:route PUT /api/v1/namespaces/{namespace}/services/{name}/status core_v1 replaceCoreV1NamespacedServiceStatus

replace status of the specified Service

*/
type ReplaceCoreV1NamespacedServiceStatus struct {
	Context *middleware.Context
	Handler ReplaceCoreV1NamespacedServiceStatusHandler
}

func (o *ReplaceCoreV1NamespacedServiceStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceCoreV1NamespacedServiceStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
