// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceCoreV1NamespacedPodHandlerFunc turns a function with the right signature into a replace core v1 namespaced pod handler
type ReplaceCoreV1NamespacedPodHandlerFunc func(ReplaceCoreV1NamespacedPodParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceCoreV1NamespacedPodHandlerFunc) Handle(params ReplaceCoreV1NamespacedPodParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceCoreV1NamespacedPodHandler interface for that can handle valid replace core v1 namespaced pod params
type ReplaceCoreV1NamespacedPodHandler interface {
	Handle(ReplaceCoreV1NamespacedPodParams, interface{}) middleware.Responder
}

// NewReplaceCoreV1NamespacedPod creates a new http.Handler for the replace core v1 namespaced pod operation
func NewReplaceCoreV1NamespacedPod(ctx *middleware.Context, handler ReplaceCoreV1NamespacedPodHandler) *ReplaceCoreV1NamespacedPod {
	return &ReplaceCoreV1NamespacedPod{Context: ctx, Handler: handler}
}

/*ReplaceCoreV1NamespacedPod swagger:route PUT /api/v1/namespaces/{namespace}/pods/{name} core_v1 replaceCoreV1NamespacedPod

replace the specified Pod

*/
type ReplaceCoreV1NamespacedPod struct {
	Context *middleware.Context
	Handler ReplaceCoreV1NamespacedPodHandler
}

func (o *ReplaceCoreV1NamespacedPod) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceCoreV1NamespacedPodParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
