// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceCoreV1NamespacedServiceHandlerFunc turns a function with the right signature into a replace core v1 namespaced service handler
type ReplaceCoreV1NamespacedServiceHandlerFunc func(ReplaceCoreV1NamespacedServiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceCoreV1NamespacedServiceHandlerFunc) Handle(params ReplaceCoreV1NamespacedServiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceCoreV1NamespacedServiceHandler interface for that can handle valid replace core v1 namespaced service params
type ReplaceCoreV1NamespacedServiceHandler interface {
	Handle(ReplaceCoreV1NamespacedServiceParams, interface{}) middleware.Responder
}

// NewReplaceCoreV1NamespacedService creates a new http.Handler for the replace core v1 namespaced service operation
func NewReplaceCoreV1NamespacedService(ctx *middleware.Context, handler ReplaceCoreV1NamespacedServiceHandler) *ReplaceCoreV1NamespacedService {
	return &ReplaceCoreV1NamespacedService{Context: ctx, Handler: handler}
}

/*ReplaceCoreV1NamespacedService swagger:route PUT /api/v1/namespaces/{namespace}/services/{name} core_v1 replaceCoreV1NamespacedService

replace the specified Service

*/
type ReplaceCoreV1NamespacedService struct {
	Context *middleware.Context
	Handler ReplaceCoreV1NamespacedServiceHandler
}

func (o *ReplaceCoreV1NamespacedService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceCoreV1NamespacedServiceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
