// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchCoreV1NamespacedEndpointsListHandlerFunc turns a function with the right signature into a watch core v1 namespaced endpoints list handler
type WatchCoreV1NamespacedEndpointsListHandlerFunc func(WatchCoreV1NamespacedEndpointsListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchCoreV1NamespacedEndpointsListHandlerFunc) Handle(params WatchCoreV1NamespacedEndpointsListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchCoreV1NamespacedEndpointsListHandler interface for that can handle valid watch core v1 namespaced endpoints list params
type WatchCoreV1NamespacedEndpointsListHandler interface {
	Handle(WatchCoreV1NamespacedEndpointsListParams, interface{}) middleware.Responder
}

// NewWatchCoreV1NamespacedEndpointsList creates a new http.Handler for the watch core v1 namespaced endpoints list operation
func NewWatchCoreV1NamespacedEndpointsList(ctx *middleware.Context, handler WatchCoreV1NamespacedEndpointsListHandler) *WatchCoreV1NamespacedEndpointsList {
	return &WatchCoreV1NamespacedEndpointsList{Context: ctx, Handler: handler}
}

/*WatchCoreV1NamespacedEndpointsList swagger:route GET /api/v1/watch/namespaces/{namespace}/endpoints core_v1 watchCoreV1NamespacedEndpointsList

watch individual changes to a list of Endpoints. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchCoreV1NamespacedEndpointsList struct {
	Context *middleware.Context
	Handler WatchCoreV1NamespacedEndpointsListHandler
}

func (o *WatchCoreV1NamespacedEndpointsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchCoreV1NamespacedEndpointsListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
