// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchCoreV1NamespacedEventListHandlerFunc turns a function with the right signature into a watch core v1 namespaced event list handler
type WatchCoreV1NamespacedEventListHandlerFunc func(WatchCoreV1NamespacedEventListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchCoreV1NamespacedEventListHandlerFunc) Handle(params WatchCoreV1NamespacedEventListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchCoreV1NamespacedEventListHandler interface for that can handle valid watch core v1 namespaced event list params
type WatchCoreV1NamespacedEventListHandler interface {
	Handle(WatchCoreV1NamespacedEventListParams, interface{}) middleware.Responder
}

// NewWatchCoreV1NamespacedEventList creates a new http.Handler for the watch core v1 namespaced event list operation
func NewWatchCoreV1NamespacedEventList(ctx *middleware.Context, handler WatchCoreV1NamespacedEventListHandler) *WatchCoreV1NamespacedEventList {
	return &WatchCoreV1NamespacedEventList{Context: ctx, Handler: handler}
}

/*WatchCoreV1NamespacedEventList swagger:route GET /api/v1/watch/namespaces/{namespace}/events core_v1 watchCoreV1NamespacedEventList

watch individual changes to a list of Event. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchCoreV1NamespacedEventList struct {
	Context *middleware.Context
	Handler WatchCoreV1NamespacedEventListHandler
}

func (o *WatchCoreV1NamespacedEventList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchCoreV1NamespacedEventListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
