// Code generated by go-swagger; DO NOT EDIT.

package storage_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteStorageV1alpha1CollectionVolumeAttachmentHandlerFunc turns a function with the right signature into a delete storage v1alpha1 collection volume attachment handler
type DeleteStorageV1alpha1CollectionVolumeAttachmentHandlerFunc func(DeleteStorageV1alpha1CollectionVolumeAttachmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteStorageV1alpha1CollectionVolumeAttachmentHandlerFunc) Handle(params DeleteStorageV1alpha1CollectionVolumeAttachmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteStorageV1alpha1CollectionVolumeAttachmentHandler interface for that can handle valid delete storage v1alpha1 collection volume attachment params
type DeleteStorageV1alpha1CollectionVolumeAttachmentHandler interface {
	Handle(DeleteStorageV1alpha1CollectionVolumeAttachmentParams, interface{}) middleware.Responder
}

// NewDeleteStorageV1alpha1CollectionVolumeAttachment creates a new http.Handler for the delete storage v1alpha1 collection volume attachment operation
func NewDeleteStorageV1alpha1CollectionVolumeAttachment(ctx *middleware.Context, handler DeleteStorageV1alpha1CollectionVolumeAttachmentHandler) *DeleteStorageV1alpha1CollectionVolumeAttachment {
	return &DeleteStorageV1alpha1CollectionVolumeAttachment{Context: ctx, Handler: handler}
}

/*DeleteStorageV1alpha1CollectionVolumeAttachment swagger:route DELETE /apis/storage.k8s.io/v1alpha1/volumeattachments storage_v1alpha1 deleteStorageV1alpha1CollectionVolumeAttachment

delete collection of VolumeAttachment

*/
type DeleteStorageV1alpha1CollectionVolumeAttachment struct {
	Context *middleware.Context
	Handler DeleteStorageV1alpha1CollectionVolumeAttachmentHandler
}

func (o *DeleteStorageV1alpha1CollectionVolumeAttachment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteStorageV1alpha1CollectionVolumeAttachmentParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
