// Code generated by go-swagger; DO NOT EDIT.

package storage_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchStorageV1beta1CSINodeHandlerFunc turns a function with the right signature into a patch storage v1beta1 c s i node handler
type PatchStorageV1beta1CSINodeHandlerFunc func(PatchStorageV1beta1CSINodeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchStorageV1beta1CSINodeHandlerFunc) Handle(params PatchStorageV1beta1CSINodeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchStorageV1beta1CSINodeHandler interface for that can handle valid patch storage v1beta1 c s i node params
type PatchStorageV1beta1CSINodeHandler interface {
	Handle(PatchStorageV1beta1CSINodeParams, interface{}) middleware.Responder
}

// NewPatchStorageV1beta1CSINode creates a new http.Handler for the patch storage v1beta1 c s i node operation
func NewPatchStorageV1beta1CSINode(ctx *middleware.Context, handler PatchStorageV1beta1CSINodeHandler) *PatchStorageV1beta1CSINode {
	return &PatchStorageV1beta1CSINode{Context: ctx, Handler: handler}
}

/*PatchStorageV1beta1CSINode swagger:route PATCH /apis/storage.k8s.io/v1beta1/csinodes/{name} storage_v1beta1 patchStorageV1beta1CSINode

partially update the specified CSINode

*/
type PatchStorageV1beta1CSINode struct {
	Context *middleware.Context
	Handler PatchStorageV1beta1CSINodeHandler
}

func (o *PatchStorageV1beta1CSINode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchStorageV1beta1CSINodeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
