// Code generated by go-swagger; DO NOT EDIT.

package storage_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchStorageV1beta1StorageClassHandlerFunc turns a function with the right signature into a watch storage v1beta1 storage class handler
type WatchStorageV1beta1StorageClassHandlerFunc func(WatchStorageV1beta1StorageClassParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchStorageV1beta1StorageClassHandlerFunc) Handle(params WatchStorageV1beta1StorageClassParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchStorageV1beta1StorageClassHandler interface for that can handle valid watch storage v1beta1 storage class params
type WatchStorageV1beta1StorageClassHandler interface {
	Handle(WatchStorageV1beta1StorageClassParams, interface{}) middleware.Responder
}

// NewWatchStorageV1beta1StorageClass creates a new http.Handler for the watch storage v1beta1 storage class operation
func NewWatchStorageV1beta1StorageClass(ctx *middleware.Context, handler WatchStorageV1beta1StorageClassHandler) *WatchStorageV1beta1StorageClass {
	return &WatchStorageV1beta1StorageClass{Context: ctx, Handler: handler}
}

/*WatchStorageV1beta1StorageClass swagger:route GET /apis/storage.k8s.io/v1beta1/watch/storageclasses/{name} storage_v1beta1 watchStorageV1beta1StorageClass

watch changes to an object of kind StorageClass. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.

*/
type WatchStorageV1beta1StorageClass struct {
	Context *middleware.Context
	Handler WatchStorageV1beta1StorageClassHandler
}

func (o *WatchStorageV1beta1StorageClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchStorageV1beta1StorageClassParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
