// Code generated by go-swagger; DO NOT EDIT.

package coordination_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchCoordinationV1beta1NamespacedLeaseListHandlerFunc turns a function with the right signature into a watch coordination v1beta1 namespaced lease list handler
type WatchCoordinationV1beta1NamespacedLeaseListHandlerFunc func(WatchCoordinationV1beta1NamespacedLeaseListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchCoordinationV1beta1NamespacedLeaseListHandlerFunc) Handle(params WatchCoordinationV1beta1NamespacedLeaseListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchCoordinationV1beta1NamespacedLeaseListHandler interface for that can handle valid watch coordination v1beta1 namespaced lease list params
type WatchCoordinationV1beta1NamespacedLeaseListHandler interface {
	Handle(WatchCoordinationV1beta1NamespacedLeaseListParams, interface{}) middleware.Responder
}

// NewWatchCoordinationV1beta1NamespacedLeaseList creates a new http.Handler for the watch coordination v1beta1 namespaced lease list operation
func NewWatchCoordinationV1beta1NamespacedLeaseList(ctx *middleware.Context, handler WatchCoordinationV1beta1NamespacedLeaseListHandler) *WatchCoordinationV1beta1NamespacedLeaseList {
	return &WatchCoordinationV1beta1NamespacedLeaseList{Context: ctx, Handler: handler}
}

/*WatchCoordinationV1beta1NamespacedLeaseList swagger:route GET /apis/coordination.k8s.io/v1beta1/watch/namespaces/{namespace}/leases coordination_v1beta1 watchCoordinationV1beta1NamespacedLeaseList

watch individual changes to a list of Lease. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchCoordinationV1beta1NamespacedLeaseList struct {
	Context *middleware.Context
	Handler WatchCoordinationV1beta1NamespacedLeaseListHandler
}

func (o *WatchCoordinationV1beta1NamespacedLeaseList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchCoordinationV1beta1NamespacedLeaseListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
