// Code generated by go-swagger; DO NOT EDIT.

package apiregistration_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchApiregistrationV1APIServiceListHandlerFunc turns a function with the right signature into a watch apiregistration v1 API service list handler
type WatchApiregistrationV1APIServiceListHandlerFunc func(WatchApiregistrationV1APIServiceListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchApiregistrationV1APIServiceListHandlerFunc) Handle(params WatchApiregistrationV1APIServiceListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchApiregistrationV1APIServiceListHandler interface for that can handle valid watch apiregistration v1 API service list params
type WatchApiregistrationV1APIServiceListHandler interface {
	Handle(WatchApiregistrationV1APIServiceListParams, interface{}) middleware.Responder
}

// NewWatchApiregistrationV1APIServiceList creates a new http.Handler for the watch apiregistration v1 API service list operation
func NewWatchApiregistrationV1APIServiceList(ctx *middleware.Context, handler WatchApiregistrationV1APIServiceListHandler) *WatchApiregistrationV1APIServiceList {
	return &WatchApiregistrationV1APIServiceList{Context: ctx, Handler: handler}
}

/*WatchApiregistrationV1APIServiceList swagger:route GET /apis/apiregistration.k8s.io/v1/watch/apiservices apiregistration_v1 watchApiregistrationV1ApiServiceList

watch individual changes to a list of APIService. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchApiregistrationV1APIServiceList struct {
	Context *middleware.Context
	Handler WatchApiregistrationV1APIServiceListHandler
}

func (o *WatchApiregistrationV1APIServiceList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchApiregistrationV1APIServiceListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
