// Code generated by go-swagger; DO NOT EDIT.

package autoscaling_v2beta2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandlerFunc turns a function with the right signature into a delete autoscaling v2beta2 collection namespaced horizontal pod autoscaler handler
type DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandlerFunc func(DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandlerFunc) Handle(params DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandler interface for that can handle valid delete autoscaling v2beta2 collection namespaced horizontal pod autoscaler params
type DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandler interface {
	Handle(DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerParams, interface{}) middleware.Responder
}

// NewDeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler creates a new http.Handler for the delete autoscaling v2beta2 collection namespaced horizontal pod autoscaler operation
func NewDeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler(ctx *middleware.Context, handler DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandler) *DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler {
	return &DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler{Context: ctx, Handler: handler}
}

/*DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler swagger:route DELETE /apis/autoscaling/v2beta2/namespaces/{namespace}/horizontalpodautoscalers autoscaling_v2beta2 deleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler

delete collection of HorizontalPodAutoscaler

*/
type DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler struct {
	Context *middleware.Context
	Handler DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerHandler
}

func (o *DeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscaler) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAutoscalingV2beta2CollectionNamespacedHorizontalPodAutoscalerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
