// Code generated by go-swagger; DO NOT EDIT.

package autoscaling_v2beta2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandlerFunc turns a function with the right signature into a read autoscaling v2beta2 namespaced horizontal pod autoscaler handler
type ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandlerFunc func(ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandlerFunc) Handle(params ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandler interface for that can handle valid read autoscaling v2beta2 namespaced horizontal pod autoscaler params
type ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandler interface {
	Handle(ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerParams, interface{}) middleware.Responder
}

// NewReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler creates a new http.Handler for the read autoscaling v2beta2 namespaced horizontal pod autoscaler operation
func NewReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler(ctx *middleware.Context, handler ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandler) *ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler {
	return &ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler{Context: ctx, Handler: handler}
}

/*ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler swagger:route GET /apis/autoscaling/v2beta2/namespaces/{namespace}/horizontalpodautoscalers/{name} autoscaling_v2beta2 readAutoscalingV2beta2NamespacedHorizontalPodAutoscaler

read the specified HorizontalPodAutoscaler

*/
type ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler struct {
	Context *middleware.Context
	Handler ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerHandler
}

func (o *ReadAutoscalingV2beta2NamespacedHorizontalPodAutoscaler) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReadAutoscalingV2beta2NamespacedHorizontalPodAutoscalerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
