// Code generated by go-swagger; DO NOT EDIT.

package authorization_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateAuthorizationV1SubjectAccessReviewHandlerFunc turns a function with the right signature into a create authorization v1 subject access review handler
type CreateAuthorizationV1SubjectAccessReviewHandlerFunc func(CreateAuthorizationV1SubjectAccessReviewParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAuthorizationV1SubjectAccessReviewHandlerFunc) Handle(params CreateAuthorizationV1SubjectAccessReviewParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateAuthorizationV1SubjectAccessReviewHandler interface for that can handle valid create authorization v1 subject access review params
type CreateAuthorizationV1SubjectAccessReviewHandler interface {
	Handle(CreateAuthorizationV1SubjectAccessReviewParams, interface{}) middleware.Responder
}

// NewCreateAuthorizationV1SubjectAccessReview creates a new http.Handler for the create authorization v1 subject access review operation
func NewCreateAuthorizationV1SubjectAccessReview(ctx *middleware.Context, handler CreateAuthorizationV1SubjectAccessReviewHandler) *CreateAuthorizationV1SubjectAccessReview {
	return &CreateAuthorizationV1SubjectAccessReview{Context: ctx, Handler: handler}
}

/*CreateAuthorizationV1SubjectAccessReview swagger:route POST /apis/authorization.k8s.io/v1/subjectaccessreviews authorization_v1 createAuthorizationV1SubjectAccessReview

create a SubjectAccessReview

*/
type CreateAuthorizationV1SubjectAccessReview struct {
	Context *middleware.Context
	Handler CreateAuthorizationV1SubjectAccessReviewHandler
}

func (o *CreateAuthorizationV1SubjectAccessReview) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateAuthorizationV1SubjectAccessReviewParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
