// Code generated by go-swagger; DO NOT EDIT.

package storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateStorageV1StorageClassHandlerFunc turns a function with the right signature into a create storage v1 storage class handler
type CreateStorageV1StorageClassHandlerFunc func(CreateStorageV1StorageClassParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateStorageV1StorageClassHandlerFunc) Handle(params CreateStorageV1StorageClassParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateStorageV1StorageClassHandler interface for that can handle valid create storage v1 storage class params
type CreateStorageV1StorageClassHandler interface {
	Handle(CreateStorageV1StorageClassParams, interface{}) middleware.Responder
}

// NewCreateStorageV1StorageClass creates a new http.Handler for the create storage v1 storage class operation
func NewCreateStorageV1StorageClass(ctx *middleware.Context, handler CreateStorageV1StorageClassHandler) *CreateStorageV1StorageClass {
	return &CreateStorageV1StorageClass{Context: ctx, Handler: handler}
}

/*CreateStorageV1StorageClass swagger:route POST /apis/storage.k8s.io/v1/storageclasses storage_v1 createStorageV1StorageClass

create a StorageClass

*/
type CreateStorageV1StorageClass struct {
	Context *middleware.Context
	Handler CreateStorageV1StorageClassHandler
}

func (o *CreateStorageV1StorageClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateStorageV1StorageClassParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
