// Code generated by go-swagger; DO NOT EDIT.

package storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteStorageV1CSINodeHandlerFunc turns a function with the right signature into a delete storage v1 c s i node handler
type DeleteStorageV1CSINodeHandlerFunc func(DeleteStorageV1CSINodeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteStorageV1CSINodeHandlerFunc) Handle(params DeleteStorageV1CSINodeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteStorageV1CSINodeHandler interface for that can handle valid delete storage v1 c s i node params
type DeleteStorageV1CSINodeHandler interface {
	Handle(DeleteStorageV1CSINodeParams, interface{}) middleware.Responder
}

// NewDeleteStorageV1CSINode creates a new http.Handler for the delete storage v1 c s i node operation
func NewDeleteStorageV1CSINode(ctx *middleware.Context, handler DeleteStorageV1CSINodeHandler) *DeleteStorageV1CSINode {
	return &DeleteStorageV1CSINode{Context: ctx, Handler: handler}
}

/*DeleteStorageV1CSINode swagger:route DELETE /apis/storage.k8s.io/v1/csinodes/{name} storage_v1 deleteStorageV1CSINode

delete a CSINode

*/
type DeleteStorageV1CSINode struct {
	Context *middleware.Context
	Handler DeleteStorageV1CSINodeHandler
}

func (o *DeleteStorageV1CSINode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteStorageV1CSINodeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
