// Code generated by go-swagger; DO NOT EDIT.

package storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReadStorageV1StorageClassHandlerFunc turns a function with the right signature into a read storage v1 storage class handler
type ReadStorageV1StorageClassHandlerFunc func(ReadStorageV1StorageClassParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReadStorageV1StorageClassHandlerFunc) Handle(params ReadStorageV1StorageClassParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReadStorageV1StorageClassHandler interface for that can handle valid read storage v1 storage class params
type ReadStorageV1StorageClassHandler interface {
	Handle(ReadStorageV1StorageClassParams, interface{}) middleware.Responder
}

// NewReadStorageV1StorageClass creates a new http.Handler for the read storage v1 storage class operation
func NewReadStorageV1StorageClass(ctx *middleware.Context, handler ReadStorageV1StorageClassHandler) *ReadStorageV1StorageClass {
	return &ReadStorageV1StorageClass{Context: ctx, Handler: handler}
}

/*ReadStorageV1StorageClass swagger:route GET /apis/storage.k8s.io/v1/storageclasses/{name} storage_v1 readStorageV1StorageClass

read the specified StorageClass

*/
type ReadStorageV1StorageClass struct {
	Context *middleware.Context
	Handler ReadStorageV1StorageClassHandler
}

func (o *ReadStorageV1StorageClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReadStorageV1StorageClassParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
