// Code generated by go-swagger; DO NOT EDIT.

package storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchStorageV1VolumeAttachmentListHandlerFunc turns a function with the right signature into a watch storage v1 volume attachment list handler
type WatchStorageV1VolumeAttachmentListHandlerFunc func(WatchStorageV1VolumeAttachmentListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchStorageV1VolumeAttachmentListHandlerFunc) Handle(params WatchStorageV1VolumeAttachmentListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchStorageV1VolumeAttachmentListHandler interface for that can handle valid watch storage v1 volume attachment list params
type WatchStorageV1VolumeAttachmentListHandler interface {
	Handle(WatchStorageV1VolumeAttachmentListParams, interface{}) middleware.Responder
}

// NewWatchStorageV1VolumeAttachmentList creates a new http.Handler for the watch storage v1 volume attachment list operation
func NewWatchStorageV1VolumeAttachmentList(ctx *middleware.Context, handler WatchStorageV1VolumeAttachmentListHandler) *WatchStorageV1VolumeAttachmentList {
	return &WatchStorageV1VolumeAttachmentList{Context: ctx, Handler: handler}
}

/*WatchStorageV1VolumeAttachmentList swagger:route GET /apis/storage.k8s.io/v1/watch/volumeattachments storage_v1 watchStorageV1VolumeAttachmentList

watch individual changes to a list of VolumeAttachment. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchStorageV1VolumeAttachmentList struct {
	Context *middleware.Context
	Handler WatchStorageV1VolumeAttachmentListHandler
}

func (o *WatchStorageV1VolumeAttachmentList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchStorageV1VolumeAttachmentListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
