// Code generated by go-swagger; DO NOT EDIT.

package autoscaling_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandlerFunc turns a function with the right signature into a replace autoscaling v1 namespaced horizontal pod autoscaler status handler
type ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandlerFunc func(ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandlerFunc) Handle(params ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandler interface for that can handle valid replace autoscaling v1 namespaced horizontal pod autoscaler status params
type ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandler interface {
	Handle(ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusParams, interface{}) middleware.Responder
}

// NewReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus creates a new http.Handler for the replace autoscaling v1 namespaced horizontal pod autoscaler status operation
func NewReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus(ctx *middleware.Context, handler ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandler) *ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus {
	return &ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus{Context: ctx, Handler: handler}
}

/*ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus swagger:route PUT /apis/autoscaling/v1/namespaces/{namespace}/horizontalpodautoscalers/{name}/status autoscaling_v1 replaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus

replace status of the specified HorizontalPodAutoscaler

*/
type ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus struct {
	Context *middleware.Context
	Handler ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusHandler
}

func (o *ReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
