// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateAppsV1NamespacedDaemonSetHandlerFunc turns a function with the right signature into a create apps v1 namespaced daemon set handler
type CreateAppsV1NamespacedDaemonSetHandlerFunc func(CreateAppsV1NamespacedDaemonSetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAppsV1NamespacedDaemonSetHandlerFunc) Handle(params CreateAppsV1NamespacedDaemonSetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateAppsV1NamespacedDaemonSetHandler interface for that can handle valid create apps v1 namespaced daemon set params
type CreateAppsV1NamespacedDaemonSetHandler interface {
	Handle(CreateAppsV1NamespacedDaemonSetParams, interface{}) middleware.Responder
}

// NewCreateAppsV1NamespacedDaemonSet creates a new http.Handler for the create apps v1 namespaced daemon set operation
func NewCreateAppsV1NamespacedDaemonSet(ctx *middleware.Context, handler CreateAppsV1NamespacedDaemonSetHandler) *CreateAppsV1NamespacedDaemonSet {
	return &CreateAppsV1NamespacedDaemonSet{Context: ctx, Handler: handler}
}

/*CreateAppsV1NamespacedDaemonSet swagger:route POST /apis/apps/v1/namespaces/{namespace}/daemonsets apps_v1 createAppsV1NamespacedDaemonSet

create a DaemonSet

*/
type CreateAppsV1NamespacedDaemonSet struct {
	Context *middleware.Context
	Handler CreateAppsV1NamespacedDaemonSetHandler
}

func (o *CreateAppsV1NamespacedDaemonSet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateAppsV1NamespacedDaemonSetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
