// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAppsV1CollectionNamespacedReplicaSetHandlerFunc turns a function with the right signature into a delete apps v1 collection namespaced replica set handler
type DeleteAppsV1CollectionNamespacedReplicaSetHandlerFunc func(DeleteAppsV1CollectionNamespacedReplicaSetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAppsV1CollectionNamespacedReplicaSetHandlerFunc) Handle(params DeleteAppsV1CollectionNamespacedReplicaSetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteAppsV1CollectionNamespacedReplicaSetHandler interface for that can handle valid delete apps v1 collection namespaced replica set params
type DeleteAppsV1CollectionNamespacedReplicaSetHandler interface {
	Handle(DeleteAppsV1CollectionNamespacedReplicaSetParams, interface{}) middleware.Responder
}

// NewDeleteAppsV1CollectionNamespacedReplicaSet creates a new http.Handler for the delete apps v1 collection namespaced replica set operation
func NewDeleteAppsV1CollectionNamespacedReplicaSet(ctx *middleware.Context, handler DeleteAppsV1CollectionNamespacedReplicaSetHandler) *DeleteAppsV1CollectionNamespacedReplicaSet {
	return &DeleteAppsV1CollectionNamespacedReplicaSet{Context: ctx, Handler: handler}
}

/*DeleteAppsV1CollectionNamespacedReplicaSet swagger:route DELETE /apis/apps/v1/namespaces/{namespace}/replicasets apps_v1 deleteAppsV1CollectionNamespacedReplicaSet

delete collection of ReplicaSet

*/
type DeleteAppsV1CollectionNamespacedReplicaSet struct {
	Context *middleware.Context
	Handler DeleteAppsV1CollectionNamespacedReplicaSetHandler
}

func (o *DeleteAppsV1CollectionNamespacedReplicaSet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAppsV1CollectionNamespacedReplicaSetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
