// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAppsV1ControllerRevisionForAllNamespacesHandlerFunc turns a function with the right signature into a list apps v1 controller revision for all namespaces handler
type ListAppsV1ControllerRevisionForAllNamespacesHandlerFunc func(ListAppsV1ControllerRevisionForAllNamespacesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAppsV1ControllerRevisionForAllNamespacesHandlerFunc) Handle(params ListAppsV1ControllerRevisionForAllNamespacesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListAppsV1ControllerRevisionForAllNamespacesHandler interface for that can handle valid list apps v1 controller revision for all namespaces params
type ListAppsV1ControllerRevisionForAllNamespacesHandler interface {
	Handle(ListAppsV1ControllerRevisionForAllNamespacesParams, interface{}) middleware.Responder
}

// NewListAppsV1ControllerRevisionForAllNamespaces creates a new http.Handler for the list apps v1 controller revision for all namespaces operation
func NewListAppsV1ControllerRevisionForAllNamespaces(ctx *middleware.Context, handler ListAppsV1ControllerRevisionForAllNamespacesHandler) *ListAppsV1ControllerRevisionForAllNamespaces {
	return &ListAppsV1ControllerRevisionForAllNamespaces{Context: ctx, Handler: handler}
}

/*ListAppsV1ControllerRevisionForAllNamespaces swagger:route GET /apis/apps/v1/controllerrevisions apps_v1 listAppsV1ControllerRevisionForAllNamespaces

list or watch objects of kind ControllerRevision

*/
type ListAppsV1ControllerRevisionForAllNamespaces struct {
	Context *middleware.Context
	Handler ListAppsV1ControllerRevisionForAllNamespacesHandler
}

func (o *ListAppsV1ControllerRevisionForAllNamespaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAppsV1ControllerRevisionForAllNamespacesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
