// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAppsV1NamespacedReplicaSetHandlerFunc turns a function with the right signature into a list apps v1 namespaced replica set handler
type ListAppsV1NamespacedReplicaSetHandlerFunc func(ListAppsV1NamespacedReplicaSetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAppsV1NamespacedReplicaSetHandlerFunc) Handle(params ListAppsV1NamespacedReplicaSetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListAppsV1NamespacedReplicaSetHandler interface for that can handle valid list apps v1 namespaced replica set params
type ListAppsV1NamespacedReplicaSetHandler interface {
	Handle(ListAppsV1NamespacedReplicaSetParams, interface{}) middleware.Responder
}

// NewListAppsV1NamespacedReplicaSet creates a new http.Handler for the list apps v1 namespaced replica set operation
func NewListAppsV1NamespacedReplicaSet(ctx *middleware.Context, handler ListAppsV1NamespacedReplicaSetHandler) *ListAppsV1NamespacedReplicaSet {
	return &ListAppsV1NamespacedReplicaSet{Context: ctx, Handler: handler}
}

/*ListAppsV1NamespacedReplicaSet swagger:route GET /apis/apps/v1/namespaces/{namespace}/replicasets apps_v1 listAppsV1NamespacedReplicaSet

list or watch objects of kind ReplicaSet

*/
type ListAppsV1NamespacedReplicaSet struct {
	Context *middleware.Context
	Handler ListAppsV1NamespacedReplicaSetHandler
}

func (o *ListAppsV1NamespacedReplicaSet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAppsV1NamespacedReplicaSetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
