// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReadAppsV1NamespacedDaemonSetStatusHandlerFunc turns a function with the right signature into a read apps v1 namespaced daemon set status handler
type ReadAppsV1NamespacedDaemonSetStatusHandlerFunc func(ReadAppsV1NamespacedDaemonSetStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReadAppsV1NamespacedDaemonSetStatusHandlerFunc) Handle(params ReadAppsV1NamespacedDaemonSetStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReadAppsV1NamespacedDaemonSetStatusHandler interface for that can handle valid read apps v1 namespaced daemon set status params
type ReadAppsV1NamespacedDaemonSetStatusHandler interface {
	Handle(ReadAppsV1NamespacedDaemonSetStatusParams, interface{}) middleware.Responder
}

// NewReadAppsV1NamespacedDaemonSetStatus creates a new http.Handler for the read apps v1 namespaced daemon set status operation
func NewReadAppsV1NamespacedDaemonSetStatus(ctx *middleware.Context, handler ReadAppsV1NamespacedDaemonSetStatusHandler) *ReadAppsV1NamespacedDaemonSetStatus {
	return &ReadAppsV1NamespacedDaemonSetStatus{Context: ctx, Handler: handler}
}

/*ReadAppsV1NamespacedDaemonSetStatus swagger:route GET /apis/apps/v1/namespaces/{namespace}/daemonsets/{name}/status apps_v1 readAppsV1NamespacedDaemonSetStatus

read status of the specified DaemonSet

*/
type ReadAppsV1NamespacedDaemonSetStatus struct {
	Context *middleware.Context
	Handler ReadAppsV1NamespacedDaemonSetStatusHandler
}

func (o *ReadAppsV1NamespacedDaemonSetStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReadAppsV1NamespacedDaemonSetStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
