// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceAppsV1NamespacedDeploymentScaleHandlerFunc turns a function with the right signature into a replace apps v1 namespaced deployment scale handler
type ReplaceAppsV1NamespacedDeploymentScaleHandlerFunc func(ReplaceAppsV1NamespacedDeploymentScaleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceAppsV1NamespacedDeploymentScaleHandlerFunc) Handle(params ReplaceAppsV1NamespacedDeploymentScaleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceAppsV1NamespacedDeploymentScaleHandler interface for that can handle valid replace apps v1 namespaced deployment scale params
type ReplaceAppsV1NamespacedDeploymentScaleHandler interface {
	Handle(ReplaceAppsV1NamespacedDeploymentScaleParams, interface{}) middleware.Responder
}

// NewReplaceAppsV1NamespacedDeploymentScale creates a new http.Handler for the replace apps v1 namespaced deployment scale operation
func NewReplaceAppsV1NamespacedDeploymentScale(ctx *middleware.Context, handler ReplaceAppsV1NamespacedDeploymentScaleHandler) *ReplaceAppsV1NamespacedDeploymentScale {
	return &ReplaceAppsV1NamespacedDeploymentScale{Context: ctx, Handler: handler}
}

/*ReplaceAppsV1NamespacedDeploymentScale swagger:route PUT /apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale apps_v1 replaceAppsV1NamespacedDeploymentScale

replace scale of the specified Deployment

*/
type ReplaceAppsV1NamespacedDeploymentScale struct {
	Context *middleware.Context
	Handler ReplaceAppsV1NamespacedDeploymentScaleHandler
}

func (o *ReplaceAppsV1NamespacedDeploymentScale) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceAppsV1NamespacedDeploymentScaleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
