// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceAppsV1NamespacedStatefulSetHandlerFunc turns a function with the right signature into a replace apps v1 namespaced stateful set handler
type ReplaceAppsV1NamespacedStatefulSetHandlerFunc func(ReplaceAppsV1NamespacedStatefulSetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceAppsV1NamespacedStatefulSetHandlerFunc) Handle(params ReplaceAppsV1NamespacedStatefulSetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceAppsV1NamespacedStatefulSetHandler interface for that can handle valid replace apps v1 namespaced stateful set params
type ReplaceAppsV1NamespacedStatefulSetHandler interface {
	Handle(ReplaceAppsV1NamespacedStatefulSetParams, interface{}) middleware.Responder
}

// NewReplaceAppsV1NamespacedStatefulSet creates a new http.Handler for the replace apps v1 namespaced stateful set operation
func NewReplaceAppsV1NamespacedStatefulSet(ctx *middleware.Context, handler ReplaceAppsV1NamespacedStatefulSetHandler) *ReplaceAppsV1NamespacedStatefulSet {
	return &ReplaceAppsV1NamespacedStatefulSet{Context: ctx, Handler: handler}
}

/*ReplaceAppsV1NamespacedStatefulSet swagger:route PUT /apis/apps/v1/namespaces/{namespace}/statefulsets/{name} apps_v1 replaceAppsV1NamespacedStatefulSet

replace the specified StatefulSet

*/
type ReplaceAppsV1NamespacedStatefulSet struct {
	Context *middleware.Context
	Handler ReplaceAppsV1NamespacedStatefulSetHandler
}

func (o *ReplaceAppsV1NamespacedStatefulSet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceAppsV1NamespacedStatefulSetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
