// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceAppsV1NamespacedControllerRevisionHandlerFunc turns a function with the right signature into a replace apps v1 namespaced controller revision handler
type ReplaceAppsV1NamespacedControllerRevisionHandlerFunc func(ReplaceAppsV1NamespacedControllerRevisionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceAppsV1NamespacedControllerRevisionHandlerFunc) Handle(params ReplaceAppsV1NamespacedControllerRevisionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceAppsV1NamespacedControllerRevisionHandler interface for that can handle valid replace apps v1 namespaced controller revision params
type ReplaceAppsV1NamespacedControllerRevisionHandler interface {
	Handle(ReplaceAppsV1NamespacedControllerRevisionParams, interface{}) middleware.Responder
}

// NewReplaceAppsV1NamespacedControllerRevision creates a new http.Handler for the replace apps v1 namespaced controller revision operation
func NewReplaceAppsV1NamespacedControllerRevision(ctx *middleware.Context, handler ReplaceAppsV1NamespacedControllerRevisionHandler) *ReplaceAppsV1NamespacedControllerRevision {
	return &ReplaceAppsV1NamespacedControllerRevision{Context: ctx, Handler: handler}
}

/*ReplaceAppsV1NamespacedControllerRevision swagger:route PUT /apis/apps/v1/namespaces/{namespace}/controllerrevisions/{name} apps_v1 replaceAppsV1NamespacedControllerRevision

replace the specified ControllerRevision

*/
type ReplaceAppsV1NamespacedControllerRevision struct {
	Context *middleware.Context
	Handler ReplaceAppsV1NamespacedControllerRevisionHandler
}

func (o *ReplaceAppsV1NamespacedControllerRevision) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceAppsV1NamespacedControllerRevisionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
