// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceAppsV1NamespacedStatefulSetScaleHandlerFunc turns a function with the right signature into a replace apps v1 namespaced stateful set scale handler
type ReplaceAppsV1NamespacedStatefulSetScaleHandlerFunc func(ReplaceAppsV1NamespacedStatefulSetScaleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceAppsV1NamespacedStatefulSetScaleHandlerFunc) Handle(params ReplaceAppsV1NamespacedStatefulSetScaleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplaceAppsV1NamespacedStatefulSetScaleHandler interface for that can handle valid replace apps v1 namespaced stateful set scale params
type ReplaceAppsV1NamespacedStatefulSetScaleHandler interface {
	Handle(ReplaceAppsV1NamespacedStatefulSetScaleParams, interface{}) middleware.Responder
}

// NewReplaceAppsV1NamespacedStatefulSetScale creates a new http.Handler for the replace apps v1 namespaced stateful set scale operation
func NewReplaceAppsV1NamespacedStatefulSetScale(ctx *middleware.Context, handler ReplaceAppsV1NamespacedStatefulSetScaleHandler) *ReplaceAppsV1NamespacedStatefulSetScale {
	return &ReplaceAppsV1NamespacedStatefulSetScale{Context: ctx, Handler: handler}
}

/*ReplaceAppsV1NamespacedStatefulSetScale swagger:route PUT /apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/scale apps_v1 replaceAppsV1NamespacedStatefulSetScale

replace scale of the specified StatefulSet

*/
type ReplaceAppsV1NamespacedStatefulSetScale struct {
	Context *middleware.Context
	Handler ReplaceAppsV1NamespacedStatefulSetScaleHandler
}

func (o *ReplaceAppsV1NamespacedStatefulSetScale) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceAppsV1NamespacedStatefulSetScaleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
