// Code generated by go-swagger; DO NOT EDIT.

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchAppsV1NamespacedStatefulSetListHandlerFunc turns a function with the right signature into a watch apps v1 namespaced stateful set list handler
type WatchAppsV1NamespacedStatefulSetListHandlerFunc func(WatchAppsV1NamespacedStatefulSetListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchAppsV1NamespacedStatefulSetListHandlerFunc) Handle(params WatchAppsV1NamespacedStatefulSetListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WatchAppsV1NamespacedStatefulSetListHandler interface for that can handle valid watch apps v1 namespaced stateful set list params
type WatchAppsV1NamespacedStatefulSetListHandler interface {
	Handle(WatchAppsV1NamespacedStatefulSetListParams, interface{}) middleware.Responder
}

// NewWatchAppsV1NamespacedStatefulSetList creates a new http.Handler for the watch apps v1 namespaced stateful set list operation
func NewWatchAppsV1NamespacedStatefulSetList(ctx *middleware.Context, handler WatchAppsV1NamespacedStatefulSetListHandler) *WatchAppsV1NamespacedStatefulSetList {
	return &WatchAppsV1NamespacedStatefulSetList{Context: ctx, Handler: handler}
}

/*WatchAppsV1NamespacedStatefulSetList swagger:route GET /apis/apps/v1/watch/namespaces/{namespace}/statefulsets apps_v1 watchAppsV1NamespacedStatefulSetList

watch individual changes to a list of StatefulSet. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchAppsV1NamespacedStatefulSetList struct {
	Context *middleware.Context
	Handler WatchAppsV1NamespacedStatefulSetListHandler
}

func (o *WatchAppsV1NamespacedStatefulSetList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchAppsV1NamespacedStatefulSetListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
